const settings = [
  "Autoduelling",
  "Bronze Age",
  "Candy Land",
  "Comedic Fantasy (Discworld)",
  "Cyberpunk",
  "Dark Sun",
  "Dieselpunk",
  "Egyptian",
  "Eldritch Horror",
  "Elemental Planes",
  "Espionage",
  "Etherpunk",
  "Feywild",
  "Flood World",
  "Grimdark",
  "Hard Sci-Fi",
  "High Fantasy (LotR)",
  "Hollow Earth",
  "Iron Age",
  "Isekai",
  "Japanese Dating Sim",
  "Kaiju",
  "LitRPG",
  "Low Fantasy (Conan)",
  "Mecha",
  "Medieval Europe",
  "Modern",
  "Mythic Greece",
  "Mythic Norse",
  "Outer Planes",
  "Outer Space",
  "Pirates",
  "Post Apocalypse",
  "Roman Empire",
  "Science Fantasy (Star Wars)",
  "Science Fiction (Star Trek)",
  "Shadowfell",
  "Solarpunk",
  "Space Opera (Flash Gordon)",
  "Spelljammer",
  "Steampunk",
  "Stone Age",
  "Superheroes",
  "Swashbuckling Duellists",
  "Underdark",
  "Undersea",
  "Weird West",
  "Wild West",
  "World War I",
  "World War II",
  "World War III",
  "Wuxia",
  "Zombie Apocalypse"
]

// select a random setting
const randomSetting = settings[Math.floor(Math.random() * settings.length)];
console.log(randomSetting);
