const players = [
  "Aliens",
  "Angels",
  "Animals",
  "Assassins",
  "Barbarians",
  "Bikers",
  "Bounty Hunters",
  "Celebrities",
  "Children",
  "Clones",
  "Commoners",
  "Conspiracy Theorists",
  "Criminals",
  "Cult Members",
  "Demons",
  "Detectives",
  "Entertainers",
  "Escaped Prisoners",
  "Explorers",
  "Family",
  "Farmers",
  "Fast Food Workers",
  "Goblinoids",
  "Hackers",
  "Hitmen",
  "Influencers",
  "Inquisitors",
  "Knights",
  "Mercenaries",
  "Merchants",
  "Monks",
  "Musicians",
  "Ninjas",
  "Nobles",
  "Pirates",
  "Police",
  "Politicians",
  "Priests",
  "Refugees",
  "Retail Clerks",
  "Revolutionaries",
  "Rivals",
  "Robots",
  "Salesmen",
  "Savage Tribesmen",
  "Scientists",
  "Siblings",
  "Smugglers",
  "Soldiers",
  "Spies",
  "Stewardesses",
  "Students",
  "Survivalists",
  "Teachers",
  "Thieves",
  "Time Travelers",
  "Treasure Hunters",
  "Undead",
  "Veterans",
  "Vikings",
  "War Buddies",
  "Wizards"
]

// select a random player
const randomPlayer = players[Math.floor(Math.random() * players.length)];
console.log(randomPlayer);
