const plots = [
  "2001: A Space Odyssey",
  "A Nightmare on Elm Street",
  "Airplane!",
  "Alien",
  "Animal House",
  "Army of Darkness",
  "Big Trouble in Little China",
  "Blade Runner",
  "Braveheart",
  "Breaking Bad",
  "Brewster's Millions",
  "Caddyshack",
  "Close Encounters of the Third Kind",
  "Conan the Barbarian",
  "Dawn of the Dead",
  "Day of the Triffids",
  "Die Hard",
  "Dr. Strangelove",
  "E.T. the Extra-Terrestrial",
  "Escape from New York",
  "Event Horizon",
  "Fargo",
  "Ferris Bueller's Day Off",
  "Fight Club",
  "Galaxy Quest",
  "Ghostbusters",
  "Gladiator",
  "Godzilla",
  "Groundhog Day",
  "James Bond",
  "Jaws",
  "Johnny Dangerously",
  "Jurassic Park",
  "Logan's Run",
  "M*A*S*H",
  "Mad Max",
  "Maverick",
  "Mission: Impossible",
  "Mortal Kombat",
  "National Lampoon's Vacation",
  "O Brother, Where Art Thou?",
  "Oklahoma!",
  "Pirates of the Caribbean",
  "Plan 9 From Outer Space",
  "Police Academy",
  "Poltergeist",
  "Predator",
  "Raiders of the Lost Ark",
  "Red Dawn",
  "RoboCop",
  "Run Silent, Run Deep",
  "Saving Private Ryan",
  "Smokey and the Bandit",
  "Speed",
  "Star Wars",
  "Starship Troopers",
  "Terminator",
  "The Adventures of Buckaroo Banzai",
  "The Big Lebowski",
  "The Blair Witch Project",
  "The Blues Brothers",
  "The Dirty Dozen",
  "The Fifth Element",
  "The Good, the Bad and the Ugly",
  "The Goonies",
  "The Hunger Games",
  "The Italian Job",
  "The Island of Doctor Moreau",
  "The Lost Room",
  "The Matrix",
  "The Princess Bride",
  "The Shining",
  "The Walking Dead",
  "The Warriors",
  "The Wizard of Oz",
  "They Live",
  "Titanic",
  "Total Recall",
  "Tremors",
  "Tron",
  "Wargames",
  "Weekend at Bernie's"
]

// select a random plot
const randomPlot = plots[Math.floor(Math.random() * plots.length)];
console.log(randomPlot);
